#!/bin/bash

if ! command -v pwsh >/dev/null 2>&1 ; then
    echo "PowerShell is required!"

    exit 1
fi

module="$HOME/.dotman/install.ps1"

if [[ -f "$module" ]]; then
    pwsh "$module" "$@"
else
    echo "Module is missing!"

    exit 1
fi
